### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by retronbv** [robalb/morsechat#8]
Idk if this is still active or not, but I’m setting up my own instance of this. I have the pusher all setup but cannot for the life of me find the `makepassword.php` file! Please help

**Comment by robalb** [comment]
Yeah this project has been organized pretty badly i'm sorry you have to go through it.
That file had a security issue and got deleted in a previous commit. You can ignore everything related to the admin settings, everything works fine without them

**Comment by YOYITsM3M8** [comment]
> Yeah this project has been organized pretty badly i'm sorry you have to go through it.
> That file had a security issue and got deleted in a previous commit. You can ignore everything related to the admin settings, everything works fine without them

Ok, so now it is telling me
```[Wed Dec 16 12:30:42 2020] PHP Warning:  file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/runner/morsechat/app/auth.php on line 64
[Wed Dec 16 12:30:42 2020] PHP Warning:  file_get_contents(http://getcitydetails.geobytes.com/GetCityDetails?fqcn=172.18.0.1): failed to open stream: php_network_getaddresses: getaddrinfo failed: Name or service not known in /home/runner/morsechat/app/auth.php on line 64
[Wed Dec 16 12:30:42 2020] PHP Fatal error:  Uncaught Pusher\PusherException: The Pusher library requires the PHP cURL module. Please ensure it is installed in /home/runner/morsechat/app/pusher/Pusher.php:175
Stack trace:
#0 /home/runner/morsechat/app/pusher/Pusher.php(45): Pusher\Pusher->check_compatibility()
#1 /home/runner/morsechat/app/auth.php(133): Pusher\Pusher->__construct('96ff5aa32946ff0...', 'fbc77dfb4c40065...', '1123570', Array)
#2 {main}
  thrown in /home/runner/morsechat/app/pusher/Pusher.php on line 175
[Wed Dec 16 12:30:42 2020] 172.18.0.1:60362 [500]: /app/auth.php - Uncaught Pusher\PusherException: The Pusher library requires the PHP cURL module. Please ensure it is installed in /home/runner/morsechat/app/pusher/Pusher.php:175
Stack trace:
#0 /home/runner/morsechat/app/pusher/Pusher.php(45): Pusher\Pusher->check_compatibility()
#1 /home/runner/morsechat/app/auth.php(133): Pusher\Pusher->__construct('96ff5aa32946ff0...', 'fbc77dfb4c40065...', '1123570', Array)
#2 {main}
  thrown in /home/runner/morsechat/app/pusher/Pusher.php on line 175```
